=== assertmyself/gweb-v2/src/IM/IAD/im.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--信息模型schema，保存了类表，属性表，枚举表，snmp映射信息-->
<im:schema xmlns:im="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<im:element name="attrElement">
		<im:complexType mixed="true">
			<im:attribute name="name" use="required">
				<im:simpleType>
					<im:restriction base="im:string"> 
						<im:enumeration value="AttrName"/>
						<im:enumeration value="AliasName"/>
						<im:enumeration value="DataType"/>
						<im:enumeration value="ControlType"/>
						<im:enumeration value="DefaultValue"/>
						<im:enumeration value="MinValue"/>
						<im:enumeration value="MaxValue"/>
						<im:enumeration value="Mask"/>		
						<im:enumeration value="Length"/>
						<im:enumeration value="RelationCid"/>
					</im:restriction>
				</im:simpleType>
			</im:attribute>
		</im:complexType>
	</im:element>
	<im:element name="attribute">
		<im:complexType>
			<im:sequence>
				<im:element ref="attrElement" maxOccurs="unbounded"/>
				<im:element ref="enum" minOccurs="0" maxOccurs="unbounded"/>
			</im:sequence>
			<im:attribute name="id" type="im:positiveInteger" use="required"/>
		</im:complexType>
	</im:element>
	<im:element name="class">
		<im:complexType>
			<im:sequence>
				<im:element ref="classElement" maxOccurs="unbounded"/>
				<im:element ref="attribute" minOccurs="0" maxOccurs="unbounded"/>
				<im:element ref="snmp" minOccurs="0"/>
				<im:element ref="class" minOccurs="0" maxOccurs="unbounded"/>
				<im:element ref="childNe" minOccurs="0" maxOccurs="unbounded"/>
			</im:sequence>
			<im:attribute name="id" type="im:positiveInteger" use="required"/>
			<im:attribute name="name" type="im:string" use="required"/>
		</im:complexType>
	</im:element>
	<im:element name="childNe">
		<im:complexType>
			<im:attribute name="type" type="im:string" use="required"/>
		</im:complexType>
	</im:element>
	<im:element name="classElement">
		<im:complexType mixed="true">
			<im:attribute name="name" use="required">
				<im:simpleType>
					<im:restriction base="im:string">
						<im:enumeration value="aliasName"/>
						<im:enumeration value="tableName"/>
						<im:enumeration value="scalar"/>
					</im:restriction>
				</im:simpleType>
			</im:attribute>
		</im:complexType>
	</im:element>
	<im:element name="entry">
		<im:complexType mixed="true">
			<im:attribute name="value" type="im:integer" use="required"/>
		</im:complexType>
	</im:element>
	<im:element name="enum">
		<im:complexType>
			<im:sequence>
				<im:element ref="entry" minOccurs="0" maxOccurs="unbounded"/>
			</im:sequence>
			<im:attribute name="groupId" type="im:integer" use="required"/>
			<im:attribute name="groupName" type="im:string" use="required"/>
			<im:attribute name="editable" type="im:boolean" use="optional" default="false"/>
		</im:complexType>
	</im:element>
	<im:element name="get">
		<im:complexType>
			<im:sequence>
				<im:element ref="param" minOccurs="1"  maxOccurs="unbounded"/>
			</im:sequence>
		</im:complexType>
	</im:element>
	<im:element name="im">
		<im:complexType>
			<im:sequence>
				<im:element ref="class"/>
			</im:sequence>
			<im:attribute name="version" type="im:string" use="required"/>
			<im:attribute name="type" type="im:string" use="required"/>
			<im:attribute name="desc" type="im:string" use="required"/>
		</im:complexType>
	</im:element>
	<im:element name="index"> 
		<im:complexType>
			<im:sequence>
				<im:element ref="aid" minOccurs="1" maxOccurs="unbounded"/>
			</im:sequence>
		</im:complexType>
	</im:element>
	<im:element name="aid" type="im:string"/>
	<im:element name="operation">
		<im:complexType>
			<im:sequence>
				<im:element ref="param" minOccurs="1" maxOccurs="unbounded"/>
			</im:sequence>
			<im:attribute name="name" type="im:string" use="required"/>
		</im:complexType>
	</im:element>
	<im:element name="param">
		<im:complexType mixed="true"> 
			<im:attribute name="name" type="im:string" use="required"/>
		</im:complexType>
	</im:element>
	<im:element name="set">
		<im:complexType>
			<im:sequence>
				<im:element ref="param" minOccurs="1" maxOccurs="unbounded"/>
			</im:sequence>
		</im:complexType>
	</im:element>
</im:schema>

=== assertmyself/gweb-v2/src/IM/GBCOM/GBCOM_CAR_1.0.0_im.xml
<?xml version="1.0" encoding="UTF-8"?>
<im xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" desc="" type="GBCOM_CAR" version="1.0.0" xsi:noNamespaceSchemaLocation="im.xsd">

    <class id="0" name="GBCOM_CAR">
        <classElement name="aliasName">模拟小车</classElement>            <!-- 设备中文名 -->
        <!-- 报警列表，包括告警、事件等设备主动上报的信息  -->
        <classElement name="alarmParser">com.gbcom.common.im.parse.alarm.EmptyAlarmParser</classElement>  <!-- 告警上报/清除的处理类 -->
        <classElement name="rspParser"></classElement>  <!-- 应答消息处理类 -->
        <!-- 属性列表  -->

        <!--  启动/熄火设置 -->
        <attribute id="1">
            <attrElement name="AttrName">power</attrElement>    <!-- 英文名称,可以与按键名一致 -->
            <attrElement name="AliasName">启动/熄火</attrElement>          <!-- 中文名称 -->
            <attrElement name="DataType">1</attrElement>                  <!-- 数据类型 -->
            <attrElement name="DefaultValue">0</attrElement>          <!-- 缺省值 -->
            <attrElement name="MinValue">0</attrElement>              <!-- 最小值 -->
            <attrElement name="MaxValue">1</attrElement>            <!-- 最大值 -->
            <attrElement name="Length">1</attrElement>                <!-- 长度 -->
            <attrElement name="AtCmd"></attrElement>    <!-- 发送AT指令，支持pattern适配value；如果有枚举值，则该项可以不填 -->
            <attrElement name="RspParser"></attrElement>        	  <!-- 接收应答的处理类 -->
            <enum groupId="0" groupName="">
                <entry value="0" name="熄火">A5A5A5A50000101210{SN}{CRC32}</entry>   <!-- AT指令 -->
                <entry value="1" name="启动">A5A5A5A50000101010{SN}{CRC32}</entry>   <!-- AT指令 -->
            </enum>
        </attribute>

        <!-- 档位设置 -->
        <attribute id="2">
            <attrElement name="AttrName">geer</attrElement>    <!-- 英文名称,可以与按键名一致 -->
            <attrElement name="AliasName">档位</attrElement>          <!-- 中文名称 -->
            <attrElement name="DataType">1</attrElement>                  <!-- 数据类型 -->
            <attrElement name="DefaultValue">0</attrElement>          <!-- 缺省值 -->
            <attrElement name="MinValue">0</attrElement>              <!-- 最小值 -->
            <attrElement name="MaxValue">2</attrElement>            <!-- 最大值 -->
            <attrElement name="Length">1</attrElement>                <!-- 长度 -->
            <attrElement name="AtCmd"></attrElement>    <!-- 发送AT指令，支持pattern适配value；如果有枚举值，则该项可以不填 -->
            <attrElement name="RspParser"></attrElement>        	  <!-- 接收应答的处理类 -->
            <enum groupId="0" groupName="">
                <entry value="0" name="P档">A5A5A5A50000101810{SN}{CRC32}</entry>   <!-- AT指令 -->
                <entry value="1" name="R档">A5A5A5A50000101610{SN}{CRC32}</entry>   <!-- AT指令 -->
                <entry value="2" name="D档">A5A5A5A50000101410{SN}{CRC32}</entry>   <!-- AT指令 -->
            </enum>
        </attribute>

        <!-- 车速档位设置 -->
        <attribute id="3">
            <attrElement name="AttrName">speedGeer</attrElement>    <!-- 英文名称,可以与按键名一致 -->
            <attrElement name="AliasName">车速档位</attrElement>          <!-- 中文名称 -->
            <attrElement name="DataType">1</attrElement>                  <!-- 数据类型 -->
            <attrElement name="DefaultValue">1</attrElement>          <!-- 缺省值 -->
            <attrElement name="MinValue">1</attrElement>              <!-- 最小值 -->
            <attrElement name="MaxValue">4</attrElement>            <!-- 最大值 -->
            <attrElement name="Length">1</attrElement>                <!-- 长度 -->
            <attrElement name="AtCmd"></attrElement>    <!-- 发送AT指令，支持pattern适配value；如果有枚举值，则该项可以不填 -->
            <attrElement name="RspParser"></attrElement>        	  <!-- 接收应答的处理类 -->
            <enum groupId="0" groupName="">
                <entry value="1" name="1档">A5A5A5A50000102211{SN}{CRC32}01</entry>   <!-- AT指令 -->
                <entry value="2" name="2档">A5A5A5A50000102211{SN}{CRC32}02</entry>   <!-- AT指令 -->
                <entry value="3" name="3档">A5A5A5A50000102211{SN}{CRC32}03</entry>   <!-- AT指令 -->
                <entry value="4" name="4档">A5A5A5A50000102211{SN}{CRC32}04</entry>   <!-- AT指令 -->
            </enum>
        </attribute>

        <!-- LCD颜色设置 -->
        <attribute id="4">
            <attrElement name="AttrName">color</attrElement>    <!-- 英文名称,可以与按键名一致 -->
            <attrElement name="AliasName">LED灯颜色</attrElement>          <!-- 中文名称 -->
            <attrElement name="DataType">11</attrElement>                  <!-- 数据类型 -->   <!-- 单字节数组 -->
            <attrElement name="DefaultValue">0</attrElement>          <!-- 缺省值 -->
            <attrElement name="MinValue">0</attrElement>              <!-- 最小值 -->
            <attrElement name="MaxValue">0</attrElement>            <!-- 最大值 -->
            <attrElement name="Length">3</attrElement>                <!-- 长度 -->
            <attrElement name="AtCmd">A5A5A5A50000102513{SN}{CRC32}{VAL}</attrElement>    <!-- 发送AT指令，支持pattern适配value；如果有枚举值，则该项可以不填 -->
            <attrElement name="RspParser"></attrElement>        	  <!-- 接收应答的处理类 -->
        </attribute>

        <!-- LCD字符设置 -->
        <attribute id="5">
            <attrElement name="AttrName">character</attrElement>    <!-- 英文名称,可以与按键名一致 -->
            <attrElement name="AliasName">字符显示</attrElement>          <!-- 中文名称 -->
            <attrElement name="DataType">5</attrElement>                  <!-- 数据类型 -->   <!-- 单字节数组 -->
            <attrElement name="DefaultValue"></attrElement>          <!-- 缺省值 -->
            <attrElement name="MinValue">0</attrElement>              <!-- 最小值 -->
            <attrElement name="MaxValue">20</attrElement>            <!-- 最大值 -->
            <attrElement name="Length">20</attrElement>                <!-- 长度 -->
            <attrElement name="AtCmd">A5A5A5A50000101E24{SN}{CRC32}{VAL}</attrElement>    <!-- 发送AT指令，支持pattern适配value；如果有枚举值，则该项可以不填 -->
            <attrElement name="RspParser"></attrElement>        	  <!-- 接收应答的处理类 -->
        </attribute>

        <!-- 操作列表，包括控制类和查询类 -->
        <!-- 查询，有应答 -->
        <!-- 设置LCD灯呼吸模式 -->
        <opt group="1" id="" name="OP_CLEAR_LCD_CHAR">
            <entry key="atCmd">A5A5A5A50000102010{SN}{CRC32}</entry> 		  <!-- 发送请求AT指令 -->
            <entry key="rspParser"></entry>             	  <!-- 接收应答的处理类 -->
            <entry key="relatedAttrID"></entry>
        </opt>

        <!-- 左转 -->
        <opt group="2" id="" name="OP_TURN_LEFT">
            <entry key="atCmd">A5A5A5A50000101A10{SN}{CRC32}</entry> 		  <!-- 发送请求AT指令 -->
            <entry key="rspParser"></entry>             	  <!-- 接收应答的处理类 -->
            <entry key="relatedAttrID"></entry>
        </opt>

        <!-- 右转 -->
        <opt group="3" id="" name="OP_TURN_RIGHT">
            <entry key="atCmd">A5A5A5A50000101C10{SN}{CRC32}</entry> 		  <!-- 发送请求AT指令 -->
            <entry key="rspParser"></entry>             	  <!-- 接收应答的处理类 -->
            <entry key="relatedAttrID"></entry>
        </opt>

    </class>

</im>
